### ISSUE TITLE
Eating Animation bug with the Spice of Life mod

### ISSUE THREAD

**Issue by ghost** [Fuzss/fivefeetsmall#66]
I LOVE the aqua acrobatics eating animation, but there's a bug that occurs:

### [Here is a video briefly detailing the problem.](https://streamable.com/up9rhu)

---

Basically, the mod [Spice of Life](https://www.curseforge.com/minecraft/mc-mods/the-spice-of-life) introduces "Nutrition" and "Food Groups" into the game. It's wonderful for survival.

When a food has been eaten too many times, SoL "slows down" the speed at which the player eats. This helps the player notice when a food group isn't providing nutrition anymore.

example: If you only eat friuts too many times, eventually it will slow the eating animation down for players dramatically to indicate "hesitancy" to eat the same food over, and over, and over.

When this happens in first person there is no bug. But in 3rd person, with the Aqua Acrobatics eating animation, there is a crazy arm-spinning but that occurs.

I'm aware I can fix this by disabling Aqua Acrobatics eating animation, but I was hoping to see integration between the two! I'll send you a $25 amazon giftcard. I know it's not much, but I appreciate your time!

**Comment by embeddedt** [comment]
Fixed in 1.8.1. No need to worry about the gift card. :slightly_smiling_face:

**Comment by ghost** [comment]
You're amazing, thank you!

**Comment by ghost** [comment]
Hi @embeddedt unfortunately this issue persists when on a Multiplayer server. No problem with singleplayer, but in Multiplayer the arm-spinning bug is still there.

**Comment by embeddedt** [comment]
Strange. That code path is supposed to be client only, but maybe Forge doesn't synchronize some values as I would expect. Please give this build a try and let me know if it works.

[aqua.zip](https://github.com/Fuzss/aquaacrobatics/files/8043731/aqua.zip)

**Comment by ghost** [comment]
Sorry, it looks like this was fixed in the latest 1.10.1 update. I had posted the bug the day before the latest update.

I can confirm that build you sent does **not** have the bug.

**Comment by embeddedt** [comment]
Hmm, there were no changes in 1.10.1 that changed the behavior here, so that's odd. In any case, the new fix is cleaner so I'll get it published on CurseForge as 1.11.0 soon.

**Comment by embeddedt** [comment]
Unfortunately, I've had to just revert the fixes for this issue entirely. From what I can tell, there is an internal desync between the client and server that results in the client not using the proper eating duration. Tthat appears to be why this bug occurs. That's also why my fixes have only worked properly in singleplayer.

At the moment I'd recommend just disabling the eating animation if you're using mods like Spice of Life.

**Comment by Ski-z** [comment]
This bug is back (as of 1.14.4), unfortunately.

**Comment by embeddedt** [comment]
As mentioned above, the underlying cause of this is unfortunately an issue in Forge and so it's not able to be fixed easily. My original fix for it was only effective in singleplayer so I reverted it.
